### ISSUE TITLE
Paper theme is now available from bower

### ISSUE THREAD

**Issue by rkmax** [log0ymxm/bootswatch-scss#24]
When i install `bower install bootswatch-scss` the paper theme is not in the latest relase

**Comment by akoskm** [comment]
Paper theme is still not downloaded, any news on this?

**Comment by paul-english** [comment]
It looks like bootswatch has scss support now. I'm no longer going to update this package. 

https://github.com/thomaspark/bootswatch/blob/gh-pages/paper/_bootswatch.scss
